MERGE INTO tblPlayerRatings AS TARGET 
USING (SELECT * FROM tblPlayer) AS SOURCE 
ON (SOURCE.playerid = TARGET.playerId) WHEN 

MATCHED THEN UPDATE 

              SET                   
                      TARGET.ModifiedOn = GETUTCDATE(),
                      TARGET.accelRating = SOURCE.accelRating, 
                      TARGET.agilityRating = SOURCE.agilityRating, 
                      TARGET.awareRating = SOURCE.awareRating, 
                      TARGET.bCVRating = SOURCE.bCVRating, 
                      TARGET.blockShedRating = SOURCE.blockShedRating, 
                      TARGET.carryRating = SOURCE.carryRating, 
                      TARGET.catchRating = SOURCE.catchRating, 
                      TARGET.cITRating = SOURCE.cITRating, 
                      TARGET.confRating = SOURCE.confRating, 
                      TARGET.changeOfDirectionRating = SOURCE.changeOfDirectionRating, 
                      TARGET.finesseMovesRating = SOURCE.finesseMovesRating, 
                      TARGET.hitPowerRating = SOURCE.hitPowerRating, 
                      TARGET.impactBlockRating = SOURCE.impactBlockRating, 
                      TARGET.injuryRating = SOURCE.injuryRating, 
                      TARGET.jukeMoveRating = SOURCE.jukeMoveRating, 
                      TARGET.jumpRating = SOURCE.jumpRating, 
                      TARGET.kickAccRating = SOURCE.kickAccRating, 
                      TARGET.kickPowerRating = SOURCE.kickPowerRating, 
                      TARGET.kickRetRating = SOURCE.kickRetRating, 
                      TARGET.manCoverRating = SOURCE.manCoverRating, 
                      TARGET.passBlockRating = SOURCE.passBlockRating, 
                      TARGET.playActionRating = SOURCE.playActionRating, 
                      TARGET.playRecRating = SOURCE.playRecRating, 
                      TARGET.powerMovesRating = SOURCE.powerMovesRating, 
                      TARGET.pressRating = SOURCE.pressRating, 
                      TARGET.pursuitRating = SOURCE.pursuitRating, 
                      TARGET.releaseRating = SOURCE.releaseRating, 
                      TARGET.routeRunRating = SOURCE.routeRunRating, 
                      TARGET.runBlockRating = SOURCE.runBlockRating, 
                      TARGET.specCatchRating = SOURCE.specCatchRating, 
                      TARGET.speedRating = SOURCE.speedRating, 
                      TARGET.spinMoveRating = SOURCE.spinMoveRating, 
                      TARGET.staminaRating = SOURCE.staminaRating, 
                      TARGET.stiffArmRating = SOURCE.stiffArmRating, 
                      TARGET.strengthRating = SOURCE.strengthRating, 
                      TARGET.tackleRating = SOURCE.tackleRating, 
                      TARGET.throwAccDeepRating = SOURCE.throwAccDeepRating, 
                      TARGET.throwAccMidRating = SOURCE.throwAccMidRating, 
                      TARGET.throwAccRating = SOURCE.throwAccRating, 
                      TARGET.throwAccShortRating = SOURCE.throwAccShortRating, 
                      TARGET.throwOnRunRating = SOURCE.throwOnRunRating, 
                      TARGET.throwPowerRating = SOURCE.throwPowerRating, 
                      TARGET.toughRating = SOURCE.toughRating, 
                      TARGET.truckRating = SOURCE.truckRating, 
                      TARGET.zoneCoverRating = SOURCE.zoneCoverRating, 
                      TARGET.breakSackRating = SOURCE.breakSackRating, 
                      TARGET.breakTackleRating = SOURCE.breakTackleRating, 
                      TARGET.leadBlockRating = SOURCE.leadBlockRating, 
                      TARGET.passBlockFinesseRating = SOURCE.passBlockFinesseRating, 
                      TARGET.passBlockPowerRating = SOURCE.passBlockPowerRating, 
                      TARGET.routeRunDeepRating = SOURCE.routeRunDeepRating, 
                      TARGET.routeRunMedRating = SOURCE.routeRunMedRating, 
                      TARGET.routeRunShortRating = SOURCE.routeRunShortRating, 
                      TARGET.runBlockFinesseRating = SOURCE.runBlockFinesseRating, 
                      TARGET.runBlockPowerRating = SOURCE.runBlockPowerRating, 
                      TARGET.throwUnderPressureRating = SOURCE.throwUnderPressureRating,
					  TARGET.playerBestOvr = SOURCE.playerBestOvr, 
                      TARGET.playerSchemeOvr = SOURCE.playerSchemeOvr, 
                      TARGET.teamSchemeOvr = SOURCE.teamSchemeOvr
 


WHEN
  NOT MATCHED BY TARGET
  THEN 

    INSERT  (playerId, 
                 leagueId, 
                 CreatedOn,
                 ModifiedOn,
                 accelRating, 
                 agilityRating, 
                 awareRating, 
                 bCVRating, 
                 blockShedRating, 
                 carryRating, 
                 catchRating, 
                 cITRating, 
                 confRating, 
                 changeOfDirectionRating, 
                 finesseMovesRating, 
                 hitPowerRating, 
                 impactBlockRating, 
                 injuryRating, 
                 jukeMoveRating, 
                 jumpRating, 
                 kickAccRating, 
                 kickPowerRating, 
                 kickRetRating, 
                 manCoverRating, 
                 passBlockRating, 
                 playActionRating, 
                 playRecRating, 
                 powerMovesRating, 
                 pressRating, 
                 pursuitRating, 
                 releaseRating, 
                 routeRunRating, 
                 runBlockRating, 
                 specCatchRating, 
                 speedRating, 
                 spinMoveRating, 
                 staminaRating, 
                 stiffArmRating, 
                 strengthRating, 
                 tackleRating, 
                 throwAccDeepRating, 
                 throwAccMidRating, 
                 throwAccRating, 
                 throwAccShortRating, 
                 throwOnRunRating, 
                 throwPowerRating, 
                 toughRating, 
                 truckRating, 
                 zoneCoverRating, 
                 breakSackRating, 
                 breakTackleRating, 
                 leadBlockRating, 
                 passBlockFinesseRating, 
                 passBlockPowerRating, 
                 routeRunDeepRating, 
                 routeRunMedRating, 
                 routeRunShortRating, 
                 runBlockFinesseRating, 
                 runBlockPowerRating, 
                 throwUnderPressureRating,				 
				 playerBestOvr,
                 playerSchemeOvr,
                 teamSchemeOvr
                )
                VALUES
                (SOURCE.playerId,
                 SOURCE.leagueId, 
                 GETUTCDATE(),
                 GETUTCDATE(),
                 SOURCE.accelRating, 
                 SOURCE.agilityRating, 
                 SOURCE.awareRating, 
                 SOURCE.bCVRating, 
                 SOURCE.blockShedRating, 
                 SOURCE.carryRating, 
                 SOURCE.catchRating, 
                 SOURCE.cITRating, 
                 SOURCE.confRating, 
                 SOURCE.changeOfDirectionRating, 
                 SOURCE.finesseMovesRating, 
                 SOURCE.hitPowerRating, 
                 SOURCE.impactBlockRating, 
                 SOURCE.injuryRating, 
                 SOURCE.jukeMoveRating, 
                 SOURCE.jumpRating, 
                 SOURCE.kickAccRating, 
                 SOURCE.kickPowerRating, 
                 SOURCE.kickRetRating, 
                 SOURCE.manCoverRating, 
                 SOURCE.passBlockRating, 
                 SOURCE.playActionRating, 
                 SOURCE.playRecRating, 
                 SOURCE.powerMovesRating, 
                 SOURCE.pressRating, 
                 SOURCE.pursuitRating, 
                 SOURCE.releaseRating, 
                 SOURCE.routeRunRating, 
                 SOURCE.runBlockRating, 
                 SOURCE.specCatchRating, 
                 SOURCE.speedRating, 
                 SOURCE.spinMoveRating, 
                 SOURCE.staminaRating, 
                 SOURCE.stiffArmRating, 
                 SOURCE.strengthRating, 
                 SOURCE.tackleRating, 
                 SOURCE.throwAccDeepRating, 
                 SOURCE.throwAccMidRating, 
                 SOURCE.throwAccRating, 
                 SOURCE.throwAccShortRating, 
                 SOURCE.throwOnRunRating, 
                 SOURCE.throwPowerRating, 
                 SOURCE.toughRating, 
                 SOURCE.truckRating, 
                 SOURCE.zoneCoverRating, 
                 SOURCE.breakSackRating, 
                 SOURCE.breakTackleRating, 
                 SOURCE.leadBlockRating, 
                 SOURCE.passBlockFinesseRating, 
                 SOURCE.passBlockPowerRating, 
                 SOURCE.routeRunDeepRating, 
                 SOURCE.routeRunMedRating, 
                 SOURCE.routeRunShortRating, 
                 SOURCE.runBlockFinesseRating, 
                 SOURCE.runBlockPowerRating, 
                 SOURCE.throwUnderPressureRating,
				 SOURCE.playerBestOvr, 
				 SOURCE.playerSchemeOvr, 
				 SOURCE.teamSchemeOvr
                );