
MERGE INTO tblPlayerTraits AS TARGET
USING
(
    SELECT *
    FROM tblPlayer
) AS SOURCE
ON(SOURCE.playerid = TARGET.playerId)
    WHEN MATCHED
    THEN UPDATE SET 
                    TARGET.ModifiedOn = GETUTCDATE(), 
                    TARGET.bigHitTrait = SOURCE.bigHitTrait, 
                    TARGET.clutchTrait = SOURCE.clutchTrait, 
                    TARGET.coverBallTrait = SOURCE.coverBallTrait, 
                    TARGET.devTrait = SOURCE.devTrait, 
                    TARGET.dLBullRushTrait = SOURCE.dLBullRushTrait, 
                    TARGET.dLSpinTrait = SOURCE.dLSpinTrait, 
                    TARGET.dLSwimTrait = SOURCE.dLSwimTrait, 
                    TARGET.dropOpenPassTrait = SOURCE.dropOpenPassTrait, 
                    TARGET.feetInBoundsTrait = SOURCE.feetInBoundsTrait, 
                    TARGET.fightForYardsTrait = SOURCE.fightForYardsTrait, 
                    TARGET.forcePassTrait = SOURCE.forcePassTrait, 
                    TARGET.highMotorTrait = SOURCE.highMotorTrait, 
                    TARGET.hPCatchTrait = SOURCE.hPCatchTrait, 
                    TARGET.lBStyleTrait = SOURCE.lBStyleTrait, 
                    TARGET.penaltyTrait = SOURCE.penaltyTrait, 
                    TARGET.playBallTrait = SOURCE.playBallTrait, 
                    TARGET.posCatchTrait = SOURCE.posCatchTrait, 
                    TARGET.predictTrait = SOURCE.predictTrait, 
                    TARGET.qBStyleTrait = SOURCE.qBStyleTrait, 
                    TARGET.sensePressureTrait = SOURCE.sensePressureTrait, 
                    TARGET.stripBallTrait = SOURCE.stripBallTrait, 
                    TARGET.throwAwayTrait = SOURCE.throwAwayTrait, 
                    TARGET.tightSpiralTrait = SOURCE.tightSpiralTrait, 
                    TARGET.yACCatchTrait = SOURCE.yACCatchTrait
    WHEN NOT MATCHED BY TARGET
    THEN
      INSERT(playerId, 
             leagueId, 
             CreatedOn, 
             ModifiedOn, 
             bigHitTrait, 
             clutchTrait, 
             coverBallTrait, 
             devTrait, 
             dLBullRushTrait, 
             dLSpinTrait, 
             dLSwimTrait, 
             dropOpenPassTrait, 
             feetInBoundsTrait, 
             fightForYardsTrait, 
             forcePassTrait, 
             highMotorTrait, 
             hPCatchTrait, 
             lBStyleTrait, 
             penaltyTrait, 
             playBallTrait, 
             posCatchTrait, 
             predictTrait, 
             qBStyleTrait, 
             sensePressureTrait, 
             stripBallTrait, 
             throwAwayTrait, 
             tightSpiralTrait, 
             yACCatchTrait)
      VALUES
            (SOURCE.playerId, 
             SOURCE.leagueId, 
             GETUTCDATE(), 
             GETUTCDATE(), 
             SOURCE.bigHitTrait, 
             SOURCE.clutchTrait, 
             SOURCE.coverBallTrait, 
             SOURCE.devTrait, 
             SOURCE.dLBullRushTrait, 
             SOURCE.dLSpinTrait, 
             SOURCE.dLSwimTrait, 
             SOURCE.dropOpenPassTrait, 
             SOURCE.feetInBoundsTrait, 
             SOURCE.fightForYardsTrait, 
             SOURCE.forcePassTrait, 
             SOURCE.highMotorTrait, 
             SOURCE.hPCatchTrait, 
             SOURCE.lBStyleTrait, 
             SOURCE.penaltyTrait, 
             SOURCE.playBallTrait, 
             SOURCE.posCatchTrait, 
             SOURCE.predictTrait, 
             SOURCE.qBStyleTrait, 
             SOURCE.sensePressureTrait, 
             SOURCE.stripBallTrait, 
             SOURCE.throwAwayTrait, 
             SOURCE.tightSpiralTrait, 
             SOURCE.yACCatchTrait
            );