 -- =============================================
-- Author:		Kevin J. Dugan Jr
-- Create date: 2017 JUNE 03
-- Description:	insert or update madden player attributes
-- =============================================

CREATE PROCEDURE [dbo].[Player_update] @leagueId                 INT, 
                                       @rosterId                 INT, 
                                       @teamId                   INT, 
                                       @portraitId               INT, 
                                       @presentationId           INT, 
                                       @injuryLength             INT, 
                                       @injuryType               INT, 
                                       @age                      INT, 
                                       @birthDay                 INT, 
                                       @birthMonth               INT, 
                                       @birthYear                INT, 
                                       @college                  VARCHAR(50), 
                                       @draftPick                INT, 
                                       @draftRound               INT, 
                                       @experiencePoints         INT, 
                                       @firstName                VARCHAR(50), 
                                       @height                   INT, 
                                       @isActive                 BIT, 
                                       @isFreeAgent              BIT, 
                                       @isOnIR                   BIT, 
                                       @isOnPracticeSquad        BIT, 
                                       @jerseyNum                INT, 
                                       @lastName                 VARCHAR(50), 
                                       @legacyScore              INT, 
                                       @playerBestOvr            INT, 
                                       @playerSchemeOvr          INT, 
                                       @position                 VARCHAR(10), 
                                       @rookieYear               INT, 
                                       @teamSchemeOvr            INT, 
                                       @weight                   INT, 
                                       @yearsPro                 INT, 
                                       @durabilityGrade          INT, 
                                       @intangibleGrade          INT, 
                                       @physicalGrade            INT, 
                                       @productionGrade          INT, 
                                       @sizeGrade                INT, 
                                       @accelRating              INT, 
                                       @agilityRating            INT, 
                                       @awareRating              INT, 
                                       @bCVRating                INT, 
                                       @blockShedRating          INT, 
                                       @carryRating              INT, 
                                       @catchRating              INT, 
                                       @cITRating                INT, 
                                       @confRating               INT, 
                                       @elusiveRating            INT, 
                                       @finesseMovesRating       INT, 
                                       @hitPowerRating           INT, 
                                       @impactBlockRating        INT, 
                                       @injuryRating             INT, 
                                       @jukeMoveRating           INT, 
                                       @jumpRating               INT, 
                                       @kickAccRating            INT, 
                                       @kickPowerRating          INT, 
                                       @kickRetRating            INT, 
                                       @manCoverRating           INT, 
                                       @passBlockRating          INT, 
                                       @playActionRating         INT, 
                                       @playRecRating            INT, 
                                       @powerMovesRating         INT, 
                                       @pressRating              INT, 
                                       @pursuitRating            INT, 
                                       @releaseRating            INT, 
                                       @routeRunRating           INT, 
                                       @runBlockRating           INT, 
                                       @specCatchRating          INT, 
                                       @speedRating              INT, 
                                       @spinMoveRating           INT, 
                                       @staminaRating            INT, 
                                       @stiffArmRating           INT, 
                                       @strengthRating           INT, 
                                       @tackleRating             INT, 
                                       @throwAccDeepRating       INT, 
                                       @throwAccMidRating        INT, 
                                       @throwAccRating           INT, 
                                       @throwAccShortRating      INT, 
                                       @throwOnRunRating         INT, 
                                       @throwPowerRating         INT, 
                                       @toughRating              INT, 
                                       @truckRating              INT, 
                                       @zoneCoverRating          INT, 
                                       @capHit                   INT, 
                                       @capReleaseNetSavings     INT, 
                                       @capReleasePenalty        INT, 
                                       @contractBonus            INT, 
                                       @contractLength           INT, 
                                       @contractSalary           INT, 
                                       @contractYearsLeft        INT, 
                                       @desiredBonus             INT, 
                                       @desiredLength            INT, 
                                       @desiredSalary            INT, 
                                       @reSignStatus             INT, 
                                       @bigHitTrait              BIT, 
                                       @clutchTrait              INT, 
                                       @coverBallTrait           INT, 
                                       @devTrait                 INT, 
                                       @dLBullRushTrait          INT, 
                                       @dLSpinTrait              INT, 
                                       @dLSwimTrait              INT, 
                                       @dropOpenPassTrait        INT, 
                                       @feetInBoundsTrait        INT, 
                                       @fightForYardsTrait       INT, 
                                       @forcePassTrait           INT, 
                                       @highMotorTrait           INT, 
                                       @hPCatchTrait             INT, 
                                       @lBStyleTrait             INT, 
                                       @penaltyTrait             INT, 
                                       @playBallTrait            INT, 
                                       @posCatchTrait            INT, 
                                       @predictTrait             INT, 
                                       @qBStyleTrait             INT, 
                                       @sensePressureTrait       INT, 
                                       @stripBallTrait           INT, 
                                       @throwAwayTrait           INT, 
                                       @tightSpiralTrait         INT, 
                                       @yACCatchTrait            INT, 
                                       @runStyle                 INT, 
                                       @scheme                   INT, 
                                       @breakSackRating          INT, 
                                       @breakTackleRating        INT, 
                                       @leadBlockRating          INT, 
                                       @passBlockFinesseRating   INT, 
                                       @passBlockPowerRating     INT, 
                                       @routeRunDeepRating       INT, 
                                       @routeRunMedRating        INT, 
                                       @routeRunShortRating      INT, 
                                       @runBlockFinesseRating    INT, 
                                       @runBlockPowerRating      INT, 
                                       @skillPoints              INT, 
                                       @throwUnderPressureRating INT
AS
    BEGIN
        -- SET NOCOUNT ON added to prevent extra result sets from
        -- interfering with SELECT statements.
        SET NOCOUNT ON;
        DECLARE @positionGroupID INT;
        SET @positionGroupID =
        (
            SELECT positionGroupID
            FROM tblPositionGroup
            WHERE Position = @position
        );
        DECLARE @playerId INT= 0;
		SET @playerId =
        (
            SELECT TOP 1 playerId
            FROM tblPlayer
			WHERE leagueId = @leagueId
				AND rosterId = @rosterId
				AND birthYear = @birthYear
				AND birthMonth = @birthMonth
				AND birthDay = @birthDay
				ORDER BY playerId ASC
        );
        
		DECLARE @teamName VARCHAR(50);
		IF(@isFreeAgent = 1)
			BEGIN
				SET @teamName = 'Free Agent'
			END
		ELSE
			BEGIN
			  SET @teamName =
					(
						SELECT displayName
						FROM tblTeamInfo
						WHERE teamId = @teamId
							  AND leagueId = @leagueId
					);
			END

        IF(@playerId > 0)
            BEGIN
                UPDATE tblPlayer
                  SET 
                      rosterId = @rosterId, 
                      lastUpdatedOn = GETDATE(), 
                      teamId = @teamId, 
                      teamName = @teamName, 
                      positionGroupID = @positionGroupID, 
                      jerseyNum = @jerseyNum, 
                      firstName = @firstName, 
                      lastName = @lastName, 
                      age = @age, 
                      injuryLength = @injuryLength, 
                      injuryType = @injuryType, 
                      experiencePoints = @experiencePoints, 
                      height = @height, 
                      isActive = @isActive, 
                      isFreeAgent = @isFreeAgent, 
                      isOnIR = @isOnIR, 
                      isOnPracticeSquad = @isOnPracticeSquad, 
                      legacyScore = @legacyScore, 
                      playerBestOvr = @playerBestOvr, 
                      playerSchemeOvr = @playerSchemeOvr, 
                      position = @position, 
                      rookieYear = @rookieYear, 
                      teamSchemeOvr = @teamSchemeOvr, 
                      [weight] = @weight, 
                      yearsPro = @yearsPro, 
                      durabilityGrade = @durabilityGrade, 
                      intangibleGrade = @intangibleGrade, 
                      physicalGrade = @physicalGrade, 
                      productionGrade = @productionGrade, 
                      sizeGrade = @sizeGrade, 
                      accelRating = @accelRating, 
                      agilityRating = @agilityRating, 
                      awareRating = @awareRating, 
                      bCVRating = @bCVRating, 
                      blockShedRating = @blockShedRating, 
                      carryRating = @carryRating, 
                      catchRating = @catchRating, 
                      cITRating = @cITRating, 
                      confRating = @confRating, 
                      elusiveRating = @elusiveRating, 
                      finesseMovesRating = @finesseMovesRating, 
                      hitPowerRating = @hitPowerRating, 
                      impactBlockRating = @impactBlockRating, 
                      injuryRating = @injuryRating, 
                      jukeMoveRating = @jukeMoveRating, 
                      jumpRating = @jumpRating, 
                      kickAccRating = @kickAccRating, 
                      kickPowerRating = @kickPowerRating, 
                      kickRetRating = @kickRetRating, 
                      manCoverRating = @manCoverRating, 
                      passBlockRating = @passBlockRating, 
                      playActionRating = @playActionRating, 
                      playRecRating = @playRecRating, 
                      powerMovesRating = @powerMovesRating, 
                      pressRating = @pressRating, 
                      pursuitRating = @pursuitRating, 
                      releaseRating = @releaseRating, 
                      routeRunRating = @routeRunRating, 
                      runBlockRating = @runBlockRating, 
                      specCatchRating = @specCatchRating, 
                      speedRating = @speedRating, 
                      spinMoveRating = @spinMoveRating, 
                      staminaRating = @staminaRating, 
                      stiffArmRating = @stiffArmRating, 
                      strengthRating = @strengthRating, 
                      tackleRating = @tackleRating, 
                      throwAccDeepRating = @throwAccDeepRating, 
                      throwAccMidRating = @throwAccMidRating, 
                      throwAccRating = @throwAccRating, 
                      throwAccShortRating = @throwAccShortRating, 
                      throwOnRunRating = @throwOnRunRating, 
                      throwPowerRating = @throwPowerRating, 
                      toughRating = @toughRating, 
                      truckRating = @truckRating, 
                      zoneCoverRating = @zoneCoverRating, 
                      capHit = @capHit, 
                      capReleaseNetSavings = @capReleaseNetSavings, 
                      capReleasePenalty = @capReleasePenalty, 
                      contractBonus = @contractBonus, 
                      contractLength = @contractLength, 
                      contractSalary = @contractSalary, 
                      contractYearsLeft = @contractYearsLeft, 
                      desiredBonus = @desiredBonus, 
                      desiredLength = @desiredLength, 
                      desiredSalary = @desiredSalary, 
                      reSignStatus = @reSignStatus, 
                      bigHitTrait = @bigHitTrait, 
                      clutchTrait = @clutchTrait, 
                      coverBallTrait = @coverBallTrait, 
                      devTrait = @devTrait, 
                      dLBullRushTrait = @dLBullRushTrait, 
                      dLSpinTrait = @dLSpinTrait, 
                      dLSwimTrait = @dLSwimTrait, 
                      dropOpenPassTrait = @dropOpenPassTrait, 
                      feetInBoundsTrait = @feetInBoundsTrait, 
                      fightForYardsTrait = @fightForYardsTrait, 
                      forcePassTrait = @forcePassTrait, 
                      highMotorTrait = @highMotorTrait, 
                      hPCatchTrait = @hPCatchTrait, 
                      lBStyleTrait = @lBStyleTrait, 
                      penaltyTrait = @penaltyTrait, 
                      playBallTrait = @playBallTrait, 
                      posCatchTrait = @posCatchTrait, 
                      predictTrait = @predictTrait, 
                      qBStyleTrait = @qBStyleTrait, 
                      sensePressureTrait = @sensePressureTrait, 
                      stripBallTrait = @stripBallTrait, 
                      throwAwayTrait = @throwAwayTrait, 
                      tightSpiralTrait = @tightSpiralTrait, 
                      yACCatchTrait = @yACCatchTrait, 
                      runStyle = @runStyle, 
                      scheme = @scheme, 
                      isRetired = 0, 
                      breakSackRating = @breakSackRating, 
                      breakTackleRating = @breakTackleRating, 
                      leadBlockRating = @leadBlockRating, 
                      passBlockFinesseRating = @passBlockFinesseRating, 
                      passBlockPowerRating = @passBlockPowerRating, 
                      routeRunDeepRating = @routeRunDeepRating, 
                      routeRunMedRating = @routeRunMedRating, 
                      routeRunShortRating = @routeRunShortRating, 
                      runBlockFinesseRating = @runBlockFinesseRating, 
                      runBlockPowerRating = @runBlockPowerRating, 
                      skillPoints = @skillPoints, 
                      throwUnderPressureRating = @throwUnderPressureRating
                WHERE playerId = @playerId
                      AND leagueId = @leagueId;
        END;
            ELSE
            BEGIN
                INSERT INTO tblPlayer
                (leagueId, 
                 rosterId, 
                 lastUpdatedOn, 
                 teamId, 
                 teamName, 
                 portraitId, 
                 presentationId, 
                 positionGroupID, 
                 jerseyNum, 
                 firstName, 
                 lastName, 
                 age, 
                 injuryLength, 
                 injuryType, 
                 birthDay, 
                 birthMonth, 
                 birthYear, 
                 college, 
                 draftPick, 
                 draftRound, 
                 experiencePoints, 
                 height, 
                 isActive, 
                 isFreeAgent, 
                 isOnIR, 
                 isOnPracticeSquad, 
                 legacyScore, 
                 playerBestOvr, 
                 playerSchemeOvr, 
                 position, 
                 rookieYear, 
                 teamSchemeOvr, 
                 [weight], 
                 yearsPro, 
                 durabilityGrade, 
                 intangibleGrade, 
                 physicalGrade, 
                 productionGrade, 
                 sizeGrade, 
                 accelRating, 
                 agilityRating, 
                 awareRating, 
                 bCVRating, 
                 blockShedRating, 
                 carryRating, 
                 catchRating, 
                 cITRating, 
                 confRating, 
                 elusiveRating, 
                 finesseMovesRating, 
                 hitPowerRating, 
                 impactBlockRating, 
                 injuryRating, 
                 jukeMoveRating, 
                 jumpRating, 
                 kickAccRating, 
                 kickPowerRating, 
                 kickRetRating, 
                 manCoverRating, 
                 passBlockRating, 
                 playActionRating, 
                 playRecRating, 
                 powerMovesRating, 
                 pressRating, 
                 pursuitRating, 
                 releaseRating, 
                 routeRunRating, 
                 runBlockRating, 
                 specCatchRating, 
                 speedRating, 
                 spinMoveRating, 
                 staminaRating, 
                 stiffArmRating, 
                 strengthRating, 
                 tackleRating, 
                 throwAccDeepRating, 
                 throwAccMidRating, 
                 throwAccRating, 
                 throwAccShortRating, 
                 throwOnRunRating, 
                 throwPowerRating, 
                 toughRating, 
                 truckRating, 
                 zoneCoverRating, 
                 capHit, 
                 capReleaseNetSavings, 
                 capReleasePenalty, 
                 contractBonus, 
                 contractLength, 
                 contractSalary, 
                 contractYearsLeft, 
                 desiredBonus, 
                 desiredLength, 
                 desiredSalary, 
                 reSignStatus, 
                 bigHitTrait, 
                 clutchTrait, 
                 coverBallTrait, 
                 devTrait, 
                 dLBullRushTrait, 
                 dLSpinTrait, 
                 dLSwimTrait, 
                 dropOpenPassTrait, 
                 feetInBoundsTrait, 
                 fightForYardsTrait, 
                 forcePassTrait, 
                 highMotorTrait, 
                 hPCatchTrait, 
                 lBStyleTrait, 
                 penaltyTrait, 
                 playBallTrait, 
                 posCatchTrait, 
                 predictTrait, 
                 qBStyleTrait, 
                 sensePressureTrait, 
                 stripBallTrait, 
                 throwAwayTrait, 
                 tightSpiralTrait, 
                 yACCatchTrait, 
                 runStyle, 
                 scheme, 
                 isRetired, 
                 breakSackRating, 
                 breakTackleRating, 
                 leadBlockRating, 
                 passBlockFinesseRating, 
                 passBlockPowerRating, 
                 routeRunDeepRating, 
                 routeRunMedRating, 
                 routeRunShortRating, 
                 runBlockFinesseRating, 
                 runBlockPowerRating, 
                 skillPoints, 
                 throwUnderPressureRating
                )
                VALUES
                (@leagueId, 
                 @rosterId, 
                 GETDATE(), 
                 @teamId, 
                 @teamName, 
                 @portraitId, 
                 @presentationId, 
                 @positionGroupID, 
                 @jerseyNum, 
                 @firstName, 
                 @lastName, 
                 @age, 
                 @injuryLength, 
                 @injuryType, 
                 @birthDay, 
                 @birthMonth, 
                 @birthYear, 
                 @college, 
                 @draftPick, 
                 @draftRound, 
                 @experiencePoints, 
                 @height, 
                 @isActive, 
                 @isFreeAgent, 
                 @isOnIR, 
                 @isOnPracticeSquad, 
                 @legacyScore, 
                 @playerBestOvr, 
                 @playerSchemeOvr, 
                 @position, 
                 @rookieYear, 
                 @teamSchemeOvr, 
                 @weight, 
                 @yearsPro, 
                 @durabilityGrade, 
                 @intangibleGrade, 
                 @physicalGrade, 
                 @productionGrade, 
                 @sizeGrade, 
                 @accelRating, 
                 @agilityRating, 
                 @awareRating, 
                 @bCVRating, 
                 @blockShedRating, 
                 @carryRating, 
                 @catchRating, 
                 @cITRating, 
                 @confRating, 
                 @elusiveRating, 
                 @finesseMovesRating, 
                 @hitPowerRating, 
                 @impactBlockRating, 
                 @injuryRating, 
                 @jukeMoveRating, 
                 @jumpRating, 
                 @kickAccRating, 
                 @kickPowerRating, 
                 @kickRetRating, 
                 @manCoverRating, 
                 @passBlockRating, 
                 @playActionRating, 
                 @playRecRating, 
                 @powerMovesRating, 
                 @pressRating, 
                 @pursuitRating, 
                 @releaseRating, 
                 @routeRunRating, 
                 @runBlockRating, 
                 @specCatchRating, 
                 @speedRating, 
                 @spinMoveRating, 
                 @staminaRating, 
                 @stiffArmRating, 
                 @strengthRating, 
                 @tackleRating, 
                 @throwAccDeepRating, 
                 @throwAccMidRating, 
                 @throwAccRating, 
                 @throwAccShortRating, 
                 @throwOnRunRating, 
                 @throwPowerRating, 
                 @toughRating, 
                 @truckRating, 
                 @zoneCoverRating, 
                 @capHit, 
                 @capReleaseNetSavings, 
                 @capReleasePenalty, 
                 @contractBonus, 
                 @contractLength, 
                 @contractSalary, 
                 @contractYearsLeft, 
                 @desiredBonus, 
                 @desiredLength, 
                 @desiredSalary, 
                 @reSignStatus, 
                 @bigHitTrait, 
                 @clutchTrait, 
                 @coverBallTrait, 
                 @devTrait, 
                 @dLBullRushTrait, 
                 @dLSpinTrait, 
                 @dLSwimTrait, 
                 @dropOpenPassTrait, 
                 @feetInBoundsTrait, 
                 @fightForYardsTrait, 
                 @forcePassTrait, 
                 @highMotorTrait, 
                 @hPCatchTrait, 
                 @lBStyleTrait, 
                 @penaltyTrait, 
                 @playBallTrait, 
                 @posCatchTrait, 
                 @predictTrait, 
                 @qBStyleTrait, 
                 @sensePressureTrait, 
                 @stripBallTrait, 
                 @throwAwayTrait, 
                 @tightSpiralTrait, 
                 @yACCatchTrait, 
                 @runStyle, 
                 @scheme, 
                 0, 
                 @breakSackRating, 
                 @breakTackleRating, 
                 @leadBlockRating, 
                 @passBlockFinesseRating, 
                 @passBlockPowerRating, 
                 @routeRunDeepRating, 
                 @routeRunMedRating, 
                 @routeRunShortRating, 
                 @runBlockFinesseRating, 
                 @runBlockPowerRating, 
                 @skillPoints, 
                 @throwUnderPressureRating
                );
        END;
    END;