-- =============================================
-- Author:		Kevin J. Dugan Jr
-- Create date: 2020 MAR 04
-- Description:	insert or update madden player ratings
-- =============================================

CREATE PROCEDURE [dbo].[PlayerRatings_update] @leagueId                 INT, 
                                              @rosterId                 INT, 
                                              @teamSchemeOvr            INT, 
                                              @playerBestOvr            INT, 
                                              @playerSchemeOvr          INT, 
                                              @accelRating              INT, 
                                              @agilityRating            INT, 
                                              @awareRating              INT, 
                                              @bCVRating                INT, 
                                              @blockShedRating          INT, 
                                              @carryRating              INT, 
                                              @catchRating              INT, 
                                              @cITRating                INT, 
                                              @confRating               INT, 
                                              @elusiveRating            INT, 
                                              @finesseMovesRating       INT, 
                                              @hitPowerRating           INT, 
                                              @impactBlockRating        INT, 
                                              @injuryRating             INT, 
                                              @jukeMoveRating           INT, 
                                              @jumpRating               INT, 
                                              @kickAccRating            INT, 
                                              @kickPowerRating          INT, 
                                              @kickRetRating            INT, 
                                              @manCoverRating           INT, 
                                              @passBlockRating          INT, 
                                              @playActionRating         INT, 
                                              @playRecRating            INT, 
                                              @powerMovesRating         INT, 
                                              @pressRating              INT, 
                                              @pursuitRating            INT, 
                                              @releaseRating            INT, 
                                              @routeRunRating           INT, 
                                              @runBlockRating           INT, 
                                              @specCatchRating          INT, 
                                              @speedRating              INT, 
                                              @spinMoveRating           INT, 
                                              @staminaRating            INT, 
                                              @stiffArmRating           INT, 
                                              @strengthRating           INT, 
                                              @tackleRating             INT, 
                                              @throwAccDeepRating       INT, 
                                              @throwAccMidRating        INT, 
                                              @throwAccRating           INT, 
                                              @throwAccShortRating      INT, 
                                              @throwOnRunRating         INT, 
                                              @throwPowerRating         INT, 
                                              @toughRating              INT, 
                                              @truckRating              INT, 
                                              @zoneCoverRating          INT, 
                                              @breakSackRating          INT, 
                                              @breakTackleRating        INT, 
                                              @leadBlockRating          INT, 
                                              @passBlockFinesseRating   INT, 
                                              @passBlockPowerRating     INT, 
                                              @routeRunDeepRating       INT, 
                                              @routeRunMedRating        INT, 
                                              @routeRunShortRating      INT, 
                                              @runBlockFinesseRating    INT, 
                                              @runBlockPowerRating      INT, 
                                              @throwUnderPressureRating INT
AS
    BEGIN
        -- SET NOCOUNT ON added to prevent extra result sets from
        -- interfering with SELECT statements.
        SET NOCOUNT ON;
        
        DECLARE @playerId INT= (dbo.fn_GetActivePlayerId(@rosterId, @leagueId));
 
        IF EXISTS (SELECT * FROM tblPlayerRatings WHERE leagueId = @leagueid AND playerId = @playerId AND playerId > 0)
            BEGIN
                UPDATE tblPlayerRatings
                  SET 
                      ModifiedOn = GetUTCDate(),

                      teamSchemeOvr = @teamSchemeOvr, 
                      playerBestOvr = @playerBestOvr, 
                      playerSchemeOvr = @playerSchemeOvr, 

                      accelRating = @accelRating, 
                      agilityRating = @agilityRating, 
                      awareRating = @awareRating, 
                      bCVRating = @bCVRating, 
                      blockShedRating = @blockShedRating, 
                      carryRating = @carryRating, 
                      catchRating = @catchRating, 
                      cITRating = @cITRating, 
                      confRating = @confRating, 
                      elusiveRating = @elusiveRating, 
                      finesseMovesRating = @finesseMovesRating, 
                      hitPowerRating = @hitPowerRating, 
                      impactBlockRating = @impactBlockRating, 
                      injuryRating = @injuryRating, 
                      jukeMoveRating = @jukeMoveRating, 
                      jumpRating = @jumpRating, 
                      kickAccRating = @kickAccRating, 
                      kickPowerRating = @kickPowerRating, 
                      kickRetRating = @kickRetRating, 
                      manCoverRating = @manCoverRating, 
                      passBlockRating = @passBlockRating, 
                      playActionRating = @playActionRating, 
                      playRecRating = @playRecRating, 
                      powerMovesRating = @powerMovesRating, 
                      pressRating = @pressRating, 
                      pursuitRating = @pursuitRating, 
                      releaseRating = @releaseRating, 
                      routeRunRating = @routeRunRating, 
                      runBlockRating = @runBlockRating, 
                      specCatchRating = @specCatchRating, 
                      speedRating = @speedRating, 
                      spinMoveRating = @spinMoveRating, 
                      staminaRating = @staminaRating, 
                      stiffArmRating = @stiffArmRating, 
                      strengthRating = @strengthRating, 
                      tackleRating = @tackleRating, 
                      throwAccDeepRating = @throwAccDeepRating, 
                      throwAccMidRating = @throwAccMidRating, 
                      throwAccRating = @throwAccRating, 
                      throwAccShortRating = @throwAccShortRating, 
                      throwOnRunRating = @throwOnRunRating, 
                      throwPowerRating = @throwPowerRating, 
                      toughRating = @toughRating, 
                      truckRating = @truckRating, 
                      zoneCoverRating = @zoneCoverRating, 
                      breakSackRating = @breakSackRating, 
                      breakTackleRating = @breakTackleRating, 
                      leadBlockRating = @leadBlockRating, 
                      passBlockFinesseRating = @passBlockFinesseRating, 
                      passBlockPowerRating = @passBlockPowerRating, 
                      routeRunDeepRating = @routeRunDeepRating, 
                      routeRunMedRating = @routeRunMedRating, 
                      routeRunShortRating = @routeRunShortRating, 
                      runBlockFinesseRating = @runBlockFinesseRating, 
                      runBlockPowerRating = @runBlockPowerRating, 
                      throwUnderPressureRating = @throwUnderPressureRating
                WHERE playerId = @playerId
                      AND leagueId = @leagueId;
        END;
            ELSE
            BEGIN
                INSERT INTO tblPlayerRatings
                (playerId, 
                 leagueId, 
                 CreatedOn,
                 ModifiedOn,
                 teamSchemeOvr,
                 playerBestOvr,
                 playerSchemeOvr,
                 accelRating, 
                 agilityRating, 
                 awareRating, 
                 bCVRating, 
                 blockShedRating, 
                 carryRating, 
                 catchRating, 
                 cITRating, 
                 confRating, 
                 elusiveRating, 
                 finesseMovesRating, 
                 hitPowerRating, 
                 impactBlockRating, 
                 injuryRating, 
                 jukeMoveRating, 
                 jumpRating, 
                 kickAccRating, 
                 kickPowerRating, 
                 kickRetRating, 
                 manCoverRating, 
                 passBlockRating, 
                 playActionRating, 
                 playRecRating, 
                 powerMovesRating, 
                 pressRating, 
                 pursuitRating, 
                 releaseRating, 
                 routeRunRating, 
                 runBlockRating, 
                 specCatchRating, 
                 speedRating, 
                 spinMoveRating, 
                 staminaRating, 
                 stiffArmRating, 
                 strengthRating, 
                 tackleRating, 
                 throwAccDeepRating, 
                 throwAccMidRating, 
                 throwAccRating, 
                 throwAccShortRating, 
                 throwOnRunRating, 
                 throwPowerRating, 
                 toughRating, 
                 truckRating, 
                 zoneCoverRating, 
                 breakSackRating, 
                 breakTackleRating, 
                 leadBlockRating, 
                 passBlockFinesseRating, 
                 passBlockPowerRating, 
                 routeRunDeepRating, 
                 routeRunMedRating, 
                 routeRunShortRating, 
                 runBlockFinesseRating, 
                 runBlockPowerRating, 
                 throwUnderPressureRating
                )
                VALUES
                (@playerId,
                 @leagueId, 
                 GETUTCDATE(),
                 GETUTCDATE(),
                 @teamSchemeOvr, 
                 @playerBestOvr, 
                 @playerSchemeOvr, 
                 @accelRating, 
                 @agilityRating, 
                 @awareRating, 
                 @bCVRating, 
                 @blockShedRating, 
                 @carryRating, 
                 @catchRating, 
                 @cITRating, 
                 @confRating, 
                 @elusiveRating, 
                 @finesseMovesRating, 
                 @hitPowerRating, 
                 @impactBlockRating, 
                 @injuryRating, 
                 @jukeMoveRating, 
                 @jumpRating, 
                 @kickAccRating, 
                 @kickPowerRating, 
                 @kickRetRating, 
                 @manCoverRating, 
                 @passBlockRating, 
                 @playActionRating, 
                 @playRecRating, 
                 @powerMovesRating, 
                 @pressRating, 
                 @pursuitRating, 
                 @releaseRating, 
                 @routeRunRating, 
                 @runBlockRating, 
                 @specCatchRating, 
                 @speedRating, 
                 @spinMoveRating, 
                 @staminaRating, 
                 @stiffArmRating, 
                 @strengthRating, 
                 @tackleRating, 
                 @throwAccDeepRating, 
                 @throwAccMidRating, 
                 @throwAccRating, 
                 @throwAccShortRating, 
                 @throwOnRunRating, 
                 @throwPowerRating, 
                 @toughRating, 
                 @truckRating, 
                 @zoneCoverRating, 
                 @breakSackRating, 
                 @breakTackleRating, 
                 @leadBlockRating, 
                 @passBlockFinesseRating, 
                 @passBlockPowerRating, 
                 @routeRunDeepRating, 
                 @routeRunMedRating, 
                 @routeRunShortRating, 
                 @runBlockFinesseRating, 
                 @runBlockPowerRating, 
                 @throwUnderPressureRating
                );
        END;
    END;