-- =============================================
-- Author:		Kevin J. Dugan Jr
-- Create date: 2017 JUNE 03
-- Description:	insert or update madden team rankings
-- =============================================
CREATE PROCEDURE [dbo].[TeamStandings_update]
	@teamId int,
    @teamName varchar(50),
    @teamOvr int,
    @calendarYear int,
    @weekIndex int,
    @seasonIndex int,
    @capRoom int,
    @capSpent int,
    @conferenceId int,
    @conferenceName varchar(50),
    @defPassYds int,
    @defPassYdsRank int,
    @defRushYds int,
    @defRushYdsRank int,
    @defTotalYds int,
    @defTotalYdsRank int,
    @divisionId int,
    @divisionName varchar(50),
    @netPts int,
    @offPassYds int,
    @offRushYds int,
    @offTotalYds int,
    @playoffStatus int,
    @prevRank int,
    @ptsAgainst int,
    @ptsFor int,
    @rank int,
    @seed int,
    @stageIndex int,
    @tODiff int,
    @totalLosses int,
    @totalTies int,
    @totalWins int,
    @winLossStreak int,
    @winPct int,
	@leagueId int

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	

  IF EXISTS (SELECT * FROM tblTeamStandings WHERE teamID = @teamId AND stageIndex = @stageIndex AND calendarYear = @calendarYear AND leagueId = @leagueId )
      UPDATE tblTeamStandings
      SET 
		teamId = @teamId,
		lastUpdatedOn = GETUTCDATE(),
		teamName = @teamName,
		teamOvr = @teamOvr,
		calendarYear = @calendarYear,
		weekIndex = @weekIndex,
		seasonIndex = @calendarYear,
		capRoom = @capRoom,
		capSpent = @capSpent,
		conferenceId = @conferenceId,
		conferenceName = @conferenceName,
		defPassYds = @defPassYds,
		defPassYdsRank = @defPassYdsRank,
		defRushYds = @defRushYds,
		defRushYdsRank = @defRushYdsRank,
		defTotalYds = @defTotalYds,
		defTotalYdsRank = @defTotalYdsRank,
		divisionId = @divisionId,
		divisionName = @divisionName,
		netPts = @netPts,
		offPassYds = @offPassYds,
		offRushYds = @offRushYds,
		offTotalYds = @offTotalYds,
		playoffStatus = @playoffStatus,
		prevRank = @prevRank,
		ptsAgainst = @ptsAgainst,
		ptsFor = @ptsFor,
		[rank] = @rank,
		seed = @seed,
		stageIndex = @stageIndex,
		tODiff = @tODiff,
		totalLosses = @totalLosses,
		totalTies = @totalTies,
		totalWins = @totalWins,
		winLossStreak = @winLossStreak,
		winPct = @winPct 
      
	  WHERE teamID = @teamId 
	  AND stageIndex  = @stageIndex  
	  AND calendarYear = @calendarYear 
	  AND leagueId = @leagueId 

   ELSE
		INSERT INTO tblTeamStandings
           (leagueId,
		   teamId,
           lastUpdatedOn,
           teamName,
           teamOvr,
           calendarYear,
           weekIndex,
           seasonIndex,
           capRoom,
           capSpent,
           conferenceId,
           conferenceName,
           defPassYds,
           defPassYdsRank,
           defRushYds,
           defRushYdsRank,
           defTotalYds,
           defTotalYdsRank,
           divisionId,
           divisionName,
           netPts,
           offPassYds,
           offRushYds,
           offTotalYds,
           playoffStatus,
           prevRank,
           ptsAgainst,
           ptsFor,
           [rank],
           seed,
           stageIndex,
           tODiff,
           totalLosses,
           totalTies,
           totalWins,
           winLossStreak,
           winPct)
     VALUES
           (@leagueId,
		    @teamId,
			GETUTCDATE(), 
			@teamName, 
			@teamOvr,
			@calendarYear,
			@weekIndex,
			@calendarYear,
			@capRoom,
			@capSpent,
			@conferenceId,
			@conferenceName, 
			@defPassYds,
			@defPassYdsRank,
			@defRushYds,
			@defRushYdsRank,
			@defTotalYds,
			@defTotalYdsRank,
			@divisionId,
			@divisionName, 
			@netPts,
			@offPassYds,
			@offRushYds,
			@offTotalYds,
			@playoffStatus,
			@prevRank,
			@ptsAgainst,
			@ptsFor,
			@rank,
			@seed,
			@stageIndex,
			@tODiff,
			@totalLosses,
			@totalTies,
			@totalWins,
			@winLossStreak,
			@winPct) 
		   
END
