CREATE TABLE [dbo].[tblPlayerProfile]
(
    [playerId]                  INT IDENTITY(1, 1) NOT NULL, 
    [rosterId]                  INT NOT NULL, 
    [leagueId]                  INT NOT NULL, 
    [CreatedOn]                 DATETIME2 NOT NULL,
    [ModifiedOn]                DATETIME2 NOT NULL,    
    [teamId]                    INT NOT NULL, 
    [teamName]                  VARCHAR(50) NOT NULL DEFAULT 'Free Agent', 
    [portraitId]                INT NOT NULL, 
    [presentationId]            INT NOT NULL, 
    [positionGroupID]           INT NOT NULL, 
    [jerseyNum]                 INT NOT NULL, 
    [fullName]                  VARCHAR(50) NULL, 
    [firstName]                 VARCHAR(50) NOT NULL, 
    [lastName]                  VARCHAR(50) NOT NULL, 
    [age]                       INT NOT NULL, 
    [injuryLength]              INT NOT NULL, 
    [injuryType]                INT NOT NULL, 
    [birthDay]                  INT NOT NULL, 
    [birthMonth]                INT NOT NULL, 
    [birthYear]                 INT NOT NULL, 
    [college]                   VARCHAR(50) NOT NULL, 
    [draftPick]                 INT NOT NULL, 
    [draftRound]                INT NOT NULL, 
    [experiencePoints]          INT NOT NULL, 
    [height]                    INT NOT NULL, 
    [isActive]                  BIT NOT NULL, 
    [isFreeAgent]               BIT NOT NULL, 
    [isOnIR]                    BIT NOT NULL, 
    [isOnPracticeSquad]         BIT NOT NULL, 
    [isRetired]                 BIT NOT NULL, 
    [legacyScore]               INT NOT NULL, 
    [position]                  VARCHAR(10) NOT NULL, 
    [rookieYear]                INT NOT NULL, 
    [rookieRating]              INT NOT NULL,         
    [weight]                    INT NOT NULL, 
    [yearsPro]                  INT NOT NULL, 
    [runStyle]                  INT NOT NULL, 
    [scheme]                    INT NOT NULL, 
    [skillPoints]               INT NULL, 
    CONSTRAINT [PK_tblPlayerProfile] PRIMARY KEY ([playerId])
)
