CREATE TABLE [dbo].[tblPlayerTraits]
(
	[playerId]                  INT NOT NULL, 
	[leagueId]                  INT NOT NULL, 
    [CreatedOn]                 DATETIME2 NOT NULL,
    [ModifiedOn]                DATETIME2 NOT NULL,
	[bigHitTrait]               INT NOT NULL, 
	[clutchTrait]               INT NOT NULL, 
	[coverBallTrait]            INT NOT NULL, 
	[devTrait]                  INT NOT NULL, 
	[dLBullRushTrait]           INT NOT NULL, 
	[dLSpinTrait]               INT NOT NULL, 
	[dLSwimTrait]               INT NOT NULL, 
	[dropOpenPassTrait]         INT NOT NULL, 
	[feetInBoundsTrait]         INT NOT NULL, 
	[fightForYardsTrait]        INT NOT NULL, 
	[forcePassTrait]            INT NOT NULL, 
	[highMotorTrait]            INT NOT NULL, 
	[hPCatchTrait]              INT NOT NULL, 
	[lBStyleTrait]              INT NOT NULL, 
	[penaltyTrait]              INT NOT NULL, 
	[playBallTrait]             INT NOT NULL, 
	[posCatchTrait]             INT NOT NULL, 
	[predictTrait]              INT NOT NULL, 
	[qBStyleTrait]              INT NOT NULL, 
	[sensePressureTrait]        INT NOT NULL, 
	[stripBallTrait]            INT NOT NULL, 
	[throwAwayTrait]            INT NOT NULL, 
	[tightSpiralTrait]          INT NOT NULL, 
	[yACCatchTrait]             INT NOT NULL, 
    PRIMARY KEY ([playerId])
)
