CREATE TABLE [dbo].[tblStatsTeam] (
    [ID]                INT             IDENTITY (1, 1) NOT NULL,
    [leagueId]          INT             NOT NULL,
    [statId]            INT             NOT NULL,
    [teamId]            INT             NOT NULL,
    [scheduleId]        INT             NOT NULL,
    [seasonIndex]       INT             NOT NULL,
    [weekIndex]         INT             NOT NULL,
    [stageIndex]        INT             NOT NULL,
    [lastUpdatedOn]     DATETIME        NOT NULL,
    [seed]              INT             NOT NULL,
    [defForcedFum]      INT             NOT NULL,
    [defFumRec]         INT             NOT NULL,
    [defIntsRec]        INT             NOT NULL,
    [defPassYds]        INT             NOT NULL,
    [defPtsPerGame]     DECIMAL (18, 6) NOT NULL,
    [defRedZoneFGs]     INT             NOT NULL,
    [defRedZonePct]     DECIMAL (18, 6) NOT NULL,
    [defRedZoneTDs]     INT             NOT NULL,
    [defRedZones]       INT             NOT NULL,
    [defRushYds]        INT             NOT NULL,
    [defSacks]          INT             NOT NULL,
    [defTotalYds]       INT             NOT NULL,
    [off1stDowns]       INT             NOT NULL,
    [off2PtAtt]         INT             NOT NULL,
    [off2PtConv]        INT             NOT NULL,
    [off2PtConvPct]     INT             NOT NULL,
    [off3rdDownAtt]     INT             NOT NULL,
    [off3rdDownConv]    INT             NOT NULL,
    [off3rdDownConvPct] DECIMAL (18, 6) NOT NULL,
    [off4thDownAtt]     INT             NOT NULL,
    [off4thDownConv]    INT             NOT NULL,
    [off4thDownConvPct] DECIMAL (18, 6) NOT NULL,
    [offFumLost]        INT             NOT NULL,
    [offIntsLost]       INT             NOT NULL,
    [offPassTDs]        INT             NOT NULL,
    [offPassYds]        INT             NOT NULL,
    [offPtsPerGame]     DECIMAL (18, 6) NOT NULL,
    [offRedZoneFGs]     INT             NOT NULL,
    [offRedZonePct]     DECIMAL (18, 6) NOT NULL,
    [offRedZoneTDs]     INT             NOT NULL,
    [offRedZones]       INT             NOT NULL,
    [offRushTDs]        INT             NOT NULL,
    [offRushYds]        INT             NOT NULL,
    [offSacks]          INT             NOT NULL,
    [offTotalYds]       INT             NOT NULL,
    [offTotalYdsGained] INT             NOT NULL,
    [penalties]         INT             NOT NULL,
    [penaltyYds]        INT             NOT NULL,
    [tODiff]            INT             NOT NULL,
    [tOGiveaways]       INT             NOT NULL,
    [tOTakeaways]       INT             NOT NULL,
    [totalLosses]       INT             NOT NULL,
    [totalTies]         INT             NOT NULL,
    [totalWins]         INT             NOT NULL,
    CONSTRAINT [PK_tblStatsTeam] PRIMARY KEY CLUSTERED ([ID] ASC)
);

