CREATE TABLE [dbo].[tblTeamStandings] (
    [ID]              INT             IDENTITY (1, 1) NOT NULL,
    [leagueId]        INT             NOT NULL,
    [teamId]          INT             NOT NULL,
    [seasonIndex]     INT             NOT NULL,
    [weekIndex]       INT             NOT NULL,
    [stageIndex]      INT             NOT NULL,
    [lastUpdatedOn]   DATETIME        NOT NULL,
    [teamName]        VARCHAR (50)    NOT NULL,
    [teamOvr]         INT             NOT NULL,
    [calendarYear]    INT             NOT NULL,
    [capRoom]         INT             NOT NULL,
    [capSpent]        INT             NOT NULL,
    [conferenceId]    INT             NOT NULL,
    [conferenceName]  VARCHAR (50)    NOT NULL,
    [defPassYds]      INT             NOT NULL,
    [defPassYdsRank]  INT             NOT NULL,
    [defRushYds]      INT             NOT NULL,
    [defRushYdsRank]  INT             NOT NULL,
    [defTotalYds]     INT             NOT NULL,
    [defTotalYdsRank] INT             NOT NULL,
    [divisionId]      INT             NOT NULL,
    [divisionName]    VARCHAR (50)    NOT NULL,
    [netPts]          INT             NOT NULL,
    [offPassYds]      INT             NOT NULL,
    [offRushYds]      INT             NOT NULL,
    [offTotalYds]     INT             NOT NULL,
    [playoffStatus]   INT             NOT NULL,
    [prevRank]        INT             NOT NULL,
    [ptsAgainst]      INT             NOT NULL,
    [ptsFor]          INT             NOT NULL,
    [rank]            INT             NOT NULL,
    [seed]            INT             NOT NULL,
    [tODiff]          INT             NOT NULL,
    [totalLosses]     INT             NOT NULL,
    [totalTies]       INT             NOT NULL,
    [totalWins]       INT             NOT NULL,
    [winLossStreak]   INT             NOT NULL,
    [winPct]          DECIMAL (18, 5) NOT NULL,
    CONSTRAINT [PK_tblTeamStandings] PRIMARY KEY CLUSTERED ([ID] ASC)
);

